### ISSUE TITLE
Something wrong with shadow-cljs or front end asset generation in general when building release?

### ISSUE THREAD

**Issue by joshlemer** [prestancedesign/pingcrm-clojure#2]
When I do an `npm run release` I get

```
> run-s -l *:release

[shadow:release ] 
[shadow:release ] > shadow:release
[shadow:release ] > shadow-cljs release app
[shadow:release ] 
[shadow:release ] shadow-cljs - config: /Users/josh/code/personal/pingcrm-clojure/shadow-cljs.edn
[shadow:release ] [:app] Compiling ...
[shadow:release ] Wrote build report to: /Users/josh/code/personal/pingcrm-clojure/public/js/report.html
[shadow:release ] [:app] Build completed. (136 files, 0 compiled, 0 warnings, 11.45s)
[postcss:release] 
[postcss:release] > postcss:release
[postcss:release] > cross-env NODE_ENV=production postcss src/css/tailwind.css -o ./public/css/app.css --verbose
[postcss:release] 
[postcss:release] Processing src/css/tailwind.css...
[postcss:release] Browserslist: caniuse-lite is outdated. Please run:
[postcss:release] npx browserslist@latest --update-db
[postcss:release] 
[postcss:release] Why you should do it regularly:
[postcss:release] https://github.com/browserslist/browserslist#browsers-data-updating
[postcss:release] Finished src/css/tailwind.css in 3.67 s
```

And then `clj -M:run`
and go to the page I find the page renders like this

<img width="1734" alt="image" src="https://user-images.githubusercontent.com/5122903/182038262-36bccda9-8136-4088-9c48-e13af05c3f6a.png">

If I go and generate the assets with dev commands like
```
npm run dev
```
and I keep the normal release-mode clojure process running (from `clj -M:run`), I navigate to the page and find the page renders normally 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/5122903/182038334-452658d7-b0f7-40c8-8975-285af8214b9f.png">

I've narrowed it down that if I manually execute
```
shadow-cljs release app
# or
shadow-cljs compile app
```
the wrong front end assets get generated but if I run `shadow-cljs watch app` the correct assets are generated.

**Comment by joshlemer** [comment]
Doing some more digging, it's definitely a problem with the generated `public/css/app.css` when doing a release. If i do a release but then overwrite the generated `public/css/app.css` with the one generated by `npm run dev`, then the problem is resolved. Also css generated by dev is 168k lines, the one generated by release is 1500 lines

**Comment by joshlemer** [comment]
The problem also resolves if you simply remove `NODE_ENV=production` from the `postcss:release` npm script:

```
        "postcss:release": "cross-env postcss src/css/tailwind.css -o ./public/css/app.css --verbose",
```

**Comment by prestancedesign** [comment]
Thank for the issue.

Seems that the Tailwind purge doesn't works anymore, I'll take a look ASAP.

**Comment by prestancedesign** [comment]
That was indeed the bug, Tailwind purge stopped working since the JS bundled filename uses now a generated hash for cache busting.
It's fixed now.

Thanks for pointing this.
